export const quoteEscrowAbi = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "beneficiary", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "availableCash",
    stateMutability: "view",
    inputs: [
      { name: "maker", type: "address" },
      { name: "token", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "cashBalance",
    stateMutability: "view",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "reservedBalance",
    stateMutability: "view",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "registerQuote",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "quote",
        type: "tuple",
        components: [
          { name: "schemaVersion", type: "uint8" },
          { name: "chainId", type: "uint256" },
          { name: "verifyingContract", type: "address" },
          { name: "maker", type: "address" },
          { name: "makerNonce", type: "uint256" },
          { name: "marketKey", type: "bytes32" },
          { name: "adapterVersion", type: "uint8" },
          { name: "positionKey", type: "bytes32" },
          { name: "collateralToken", type: "address" },
          { name: "collateralAmount", type: "uint256" },
          { name: "debtToken", type: "address" },
          { name: "cashOut", type: "uint256" },
          { name: "maxDebtRepay", type: "uint256" },
          { name: "collateralRecipient", type: "address" },
          { name: "keeperCompensation", type: "uint256" },
          { name: "protocolFee", type: "uint256" },
          { name: "minNetSurplus", type: "uint256" },
          { name: "keeperRecipient", type: "address" },
          { name: "surplusRecipient", type: "address" },
          { name: "validUntil", type: "uint64" },
          { name: "reservationId", type: "uint256" },
          { name: "policyHash", type: "bytes32" },
          { name: "quoteNonce", type: "uint256" },
        ],
      },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "hashQuote",
    stateMutability: "view",
    inputs: [
      {
        name: "q",
        type: "tuple",
        components: [
          { name: "schemaVersion", type: "uint8" },
          { name: "chainId", type: "uint256" },
          { name: "verifyingContract", type: "address" },
          { name: "maker", type: "address" },
          { name: "makerNonce", type: "uint256" },
          { name: "marketKey", type: "bytes32" },
          { name: "adapterVersion", type: "uint8" },
          { name: "positionKey", type: "bytes32" },
          { name: "collateralToken", type: "address" },
          { name: "collateralAmount", type: "uint256" },
          { name: "debtToken", type: "address" },
          { name: "cashOut", type: "uint256" },
          { name: "maxDebtRepay", type: "uint256" },
          { name: "collateralRecipient", type: "address" },
          { name: "keeperCompensation", type: "uint256" },
          { name: "protocolFee", type: "uint256" },
          { name: "minNetSurplus", type: "uint256" },
          { name: "keeperRecipient", type: "address" },
          { name: "surplusRecipient", type: "address" },
          { name: "validUntil", type: "uint64" },
          { name: "reservationId", type: "uint256" },
          { name: "policyHash", type: "bytes32" },
          { name: "quoteNonce", type: "uint256" },
        ],
      },
    ],
    outputs: [{ type: "bytes32" }],
  },
] as const;

export const executorAbi = [
  {
    type: "function",
    name: "previewJob",
    stateMutability: "view",
    inputs: [
      {
        name: "job",
        type: "tuple",
        components: [
          { name: "marketKey", type: "bytes32" },
          { name: "positionKey", type: "bytes32" },
          { name: "reservationId", type: "uint256" },
          { name: "collateralAmount", type: "uint256" },
          { name: "debtRepay", type: "uint256" },
          { name: "routeType", type: "uint8" },
          { name: "adapter", type: "address" },
        ],
      },
    ],
    outputs: [
      { name: "ok", type: "bool" },
      { name: "reason", type: "string" },
    ],
  },
] as const;
