#!/usr/bin/env node
// Exports contract ABIs (the shared source of truth) and deployment manifests to backend + web.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "contracts", "out");
const names = [
  ["MakerEscrow", "makerEscrowAbi"],
  ["QuoteRegistry", "quoteRegistryAbi"],
  ["MarketRegistry", "marketRegistryAbi"],
  ["NectarExecutor", "nectarExecutorAbi"],
  ["PauseGuard", "pauseGuardAbi"],
  ["MockLendingMarket", "mockLendingMarketAbi"],
  ["MockOracle", "mockOracleAbi"],
  ["MockERC20", "mockErc20Abi"],
  ["MockSequencerUptimeFeed", "mockSequencerUptimeFeedAbi", "MockOracle.sol"],
];

let ts = "// AUTO-GENERATED by scripts/export-abi.mjs from contracts/out. Do not edit.\n\n";
for (const [name, exportName, file] of names) {
  const p = path.join(out, file ?? `${name}.sol`, `${name}.json`);
  const abi = JSON.parse(fs.readFileSync(p, "utf8")).abi;
  ts += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}

for (const target of ["backend/src/generated", "web/src/generated"]) {
  const dir = path.join(root, target);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "abis.ts"), ts);
}

const depDir = path.join(root, "deployments");
const manifests = fs.existsSync(depDir)
  ? fs
      .readdirSync(depDir)
      .filter((f) => f.endsWith(".json"))
      .map((f) => ({ file: f, ...JSON.parse(fs.readFileSync(path.join(depDir, f), "utf8")) }))
  : [];
fs.writeFileSync(
  path.join(root, "web/src/generated/deployments.json"),
  JSON.stringify(manifests, null, 2) + "\n",
);
console.log(`exported ${names.length} ABIs and ${manifests.length} manifests`);
