// Generates packages/core/src/abis.ts from Foundry build artifacts.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const contracts = {
  testTokenAbi: "TestToken",
  mockOracleAbi: "MockOracle",
  miniMorphoAbi: "MiniMorpho",
  marketRegistryAbi: "MarketRegistry",
  makerVaultAbi: "MakerVault",
  nectarExecutorAbi: "NectarExecutor",
  demoPositionFactoryAbi: "DemoPositionFactory",
};

let src = "// AUTO-GENERATED by scripts/gen-abis.mjs from contracts/out. Do not edit.\n\n";
for (const [name, c] of Object.entries(contracts)) {
  const art = JSON.parse(readFileSync(join(out, `${c}.sol`, `${c}.json`), "utf8"));
  src += `export const ${name} = ${JSON.stringify(art.abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, "packages", "core", "src", "abis.ts"), src);
console.log("wrote packages/core/src/abis.ts");

const depDir = join(root, "deployments");
const files = readdirSync(depDir).filter((f) => /^\d+\.json$/.test(f)).sort();
let m = "// AUTO-GENERATED by scripts/gen-abis.mjs from /deployments. Do not edit.\n";
files.forEach((f, i) => (m += `import d${i} from "../../../deployments/${f}";\n`));
m += "\nexport const manifests: Record<number, unknown> = {\n";
files.forEach((f, i) => (m += `  ${f.replace(".json", "")}: d${i},\n`));
m += "};\n";
writeFileSync(join(root, "packages", "core", "src", "manifests.ts"), m);
console.log("wrote packages/core/src/manifests.ts with", files.join(", "));
